
# 日志等级
log_level = "trace"
# 日志文件
log_file = "logs/hc.log"

# lua中的环境变量
[lua_env]
aa = "bb"
cc = "dd"
zz = "this is zz ddd"
mysql = "mysql://root:guoneiqipai%^96@rm-bp14hv5146382k6t32o.mysql.rds.aliyuncs.com:3306/poker_game"